version: '3'

services:
  wp_nginx:
    image: nginx:stable
    restart: unless-stopped
    container_name: wp_nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./_docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wp-network

  wp_php: 
    build: 
      context: .
      dockerfile: _docker/wp-php/Dockerfile
    container_name: wp_php
    environment:
      DB_USER: root
      DB_PASS: devel_1234
      DB_NAME: wp
      DB_HOST: wp_db:3306
      DB_TABLE_PREFIX: wp_devel_
    volumes:
      - ./:/var/www/html  
    networks:
      - wp-network

  wp_db:
    image: mariadb:10.2
    restart: always
    container_name: wp_db
    environment:
      MYSQL_ROOT_PASSWORD: devel_1234
      MYSQL_DATABASE: wp
    ports:
      - 33061:3306
    volumes:
    - ./_docker/database:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge

